table CityPulseSnapshot
	lineageTag: 4f1df31a-a7fe-5ae9-a469-40082849a042

	column city
		dataType: string
		lineageTag: 26653aeb-f5b0-5684-8721-765d2a7563f2
		summarizeBy: none
		sourceColumn: city
		annotation SummarizationSetBy = Automatic

	column snapshot_at
		dataType: string
		lineageTag: 6d97ec0a-6a34-5c6d-b345-5e3facddf98a
		summarizeBy: none
		sourceColumn: snapshot_at
		annotation SummarizationSetBy = Automatic

	column city_stress_index
		dataType: decimal
		lineageTag: a6be2962-38bd-55e4-837b-6b6647dd2083
		summarizeBy: none
		sourceColumn: city_stress_index
		annotation SummarizationSetBy = Automatic

	column transit_load_score
		dataType: decimal
		lineageTag: df293bfd-7b03-53fa-93c8-0fadd3e596fe
		summarizeBy: none
		sourceColumn: transit_load_score
		annotation SummarizationSetBy = Automatic

	column weather_risk_score
		dataType: decimal
		lineageTag: 9e7ac00b-f243-5731-a6bd-e94ee7742701
		summarizeBy: none
		sourceColumn: weather_risk_score
		annotation SummarizationSetBy = Automatic

	column precip_risk_score
		dataType: decimal
		lineageTag: fb1cba27-c385-5734-8c07-44a61d65c80d
		summarizeBy: none
		sourceColumn: precip_risk_score
		annotation SummarizationSetBy = Automatic

	column disruption_ratio_score
		dataType: decimal
		lineageTag: 239293f8-1365-50eb-911d-a429b6181d45
		summarizeBy: none
		sourceColumn: disruption_ratio_score
		annotation SummarizationSetBy = Automatic

	column active_cta_alerts
		dataType: int64
		lineageTag: d7d21e03-ae85-5922-93d2-bdfa123bb917
		summarizeBy: sum
		sourceColumn: active_cta_alerts
		annotation SummarizationSetBy = Automatic

	column active_noaa_alerts
		dataType: int64
		lineageTag: c37b5113-06a3-5b05-8b3d-1140129de288
		summarizeBy: sum
		sourceColumn: active_noaa_alerts
		annotation SummarizationSetBy = Automatic

	column avg_precip_pct_next_periods
		dataType: decimal
		lineageTag: ea5ca68d-741f-5298-af7a-1ed590452d7c
		summarizeBy: none
		sourceColumn: avg_precip_pct_next_periods
		annotation SummarizationSetBy = Automatic

	column reroute_count
		dataType: int64
		lineageTag: 2c3b02a0-398f-5867-a858-65f42a01851a
		summarizeBy: sum
		sourceColumn: reroute_count
		annotation SummarizationSetBy = Automatic

	column delay_count
		dataType: int64
		lineageTag: 2405f1f9-5af7-5254-a387-a752367ae9b6
		summarizeBy: sum
		sourceColumn: delay_count
		annotation SummarizationSetBy = Automatic

	column airport_flight_category
		dataType: string
		lineageTag: c9befd22-8c6f-56c2-b9d8-6b48c6506af6
		summarizeBy: none
		sourceColumn: airport_flight_category
		annotation SummarizationSetBy = Automatic

	column airport_visibility_sm
		dataType: decimal
		lineageTag: dad26634-9211-51b8-93e1-2076650ea7bd
		summarizeBy: none
		sourceColumn: airport_visibility_sm
		annotation SummarizationSetBy = Automatic

	column trend_avg_interest
		dataType: decimal
		lineageTag: 452f32bd-ea6d-566a-b06a-28e2a5ac2fd2
		summarizeBy: none
		sourceColumn: trend_avg_interest
		annotation SummarizationSetBy = Automatic

	column fred_series_count
		dataType: int64
		lineageTag: 9cc1cab8-567a-5c42-860f-a47853610f0f
		summarizeBy: none
		sourceColumn: fred_series_count
		annotation SummarizationSetBy = Automatic

	measure 'City Stress Index' = AVERAGE(CityPulseSnapshot[city_stress_index])
		formatString: 0.0
		lineageTag: 96c842f7-fcb6-5afa-aacf-657c1de8088b

	measure 'Active CTA Alerts' = SUM(CityPulseSnapshot[active_cta_alerts])
		formatString: #,0
		lineageTag: 6631694e-a8b6-5479-b523-d0f5d41b1883

	measure 'Active NOAA Alerts' = SUM(CityPulseSnapshot[active_noaa_alerts])
		formatString: #,0
		lineageTag: ba942c64-41b8-59dc-bb5c-83bb9b68d30c

	measure 'Avg Precip %' = AVERAGE(CityPulseSnapshot[avg_precip_pct_next_periods])
		formatString: 0.0
		lineageTag: 80704d93-2c01-5bd8-88ec-c0d76cff2821

	measure 'Transit Load Score' = AVERAGE(CityPulseSnapshot[transit_load_score])
		formatString: 0.0
		lineageTag: fba24624-1ba9-5b79-a7a8-38b03a5415ec

	measure 'Weather Risk Score' = AVERAGE(CityPulseSnapshot[weather_risk_score])
		formatString: 0.0
		lineageTag: cb452219-f0ed-5243-becd-4fb69654fd0a

	measure 'Trend Avg Interest' = AVERAGE(CityPulseSnapshot[trend_avg_interest])
		formatString: 0.0
		lineageTag: 113123d7-469b-5c52-8be2-ffba6005e5a0

	measure 'Airport Visibility (sm)' = AVERAGE(CityPulseSnapshot[airport_visibility_sm])
		formatString: 0.0
		lineageTag: 918ab3a7-54af-5aad-9627-890d458fc1f2

	partition CityPulseSnapshot-6a9ee8ad-712d-5e82-b3a9-ef8e00d8601d = m
		mode: import
		source =
			let
				Source = Csv.Document(
					File.Contents("G:/My Drive/aq_wp_selenium_bot/aq-pulsegrid/generated_reports/chicago/data/CityPulseSnapshot.csv"),
					[Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
				),
				#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				#"Changed Column Types" = Table.TransformColumnTypes(
					#"Promoted Headers",
					{
					{"city", type text},
					{"snapshot_at", type text},
					{"city_stress_index", type number},
					{"transit_load_score", type number},
					{"weather_risk_score", type number},
					{"precip_risk_score", type number},
					{"disruption_ratio_score", type number},
					{"active_cta_alerts", Int64.Type},
					{"active_noaa_alerts", Int64.Type},
					{"avg_precip_pct_next_periods", type number},
					{"reroute_count", Int64.Type},
					{"delay_count", Int64.Type},
					{"airport_flight_category", type text},
					{"airport_visibility_sm", type number},
					{"trend_avg_interest", type number},
					{"fred_series_count", Int64.Type}
					}
				)
			in
				#"Changed Column Types"

	annotation PBI_ResultType = Table

