table CityPulseSnapshot
	lineageTag: 4f1df31a-a7fe-5ae9-a469-40082849a042

	column city
		dataType: string
		lineageTag: 26653aeb-f5b0-5684-8721-765d2a7563f2
		summarizeBy: none
		sourceColumn: city
		annotation SummarizationSetBy = Automatic

	column snapshot_at
		dataType: string
		lineageTag: 6d97ec0a-6a34-5c6d-b345-5e3facddf98a
		summarizeBy: none
		sourceColumn: snapshot_at
		annotation SummarizationSetBy = Automatic

	column city_stress_index
		dataType: decimal
		lineageTag: a6be2962-38bd-55e4-837b-6b6647dd2083
		summarizeBy: none
		sourceColumn: city_stress_index
		annotation SummarizationSetBy = Automatic

	column transit_load_score
		dataType: decimal
		lineageTag: df293bfd-7b03-53fa-93c8-0fadd3e596fe
		summarizeBy: none
		sourceColumn: transit_load_score
		annotation SummarizationSetBy = Automatic

	column weather_risk_score
		dataType: decimal
		lineageTag: 9e7ac00b-f243-5731-a6bd-e94ee7742701
		summarizeBy: none
		sourceColumn: weather_risk_score
		annotation SummarizationSetBy = Automatic

	column precip_risk_score
		dataType: decimal
		lineageTag: fb1cba27-c385-5734-8c07-44a61d65c80d
		summarizeBy: none
		sourceColumn: precip_risk_score
		annotation SummarizationSetBy = Automatic

	column disruption_ratio_score
		dataType: decimal
		lineageTag: 239293f8-1365-50eb-911d-a429b6181d45
		summarizeBy: none
		sourceColumn: disruption_ratio_score
		annotation SummarizationSetBy = Automatic

	column active_transit_alerts
		dataType: int64
		lineageTag: af7b0a0d-6d3d-5537-a496-94cd6de23123
		summarizeBy: sum
		sourceColumn: active_transit_alerts
		annotation SummarizationSetBy = Automatic

	column active_noaa_alerts
		dataType: int64
		lineageTag: c37b5113-06a3-5b05-8b3d-1140129de288
		summarizeBy: sum
		sourceColumn: active_noaa_alerts
		annotation SummarizationSetBy = Automatic

	column avg_precip_pct_next_periods
		dataType: decimal
		lineageTag: ea5ca68d-741f-5298-af7a-1ed590452d7c
		summarizeBy: none
		sourceColumn: avg_precip_pct_next_periods
		annotation SummarizationSetBy = Automatic

	column reroute_count
		dataType: int64
		lineageTag: 2c3b02a0-398f-5867-a858-65f42a01851a
		summarizeBy: sum
		sourceColumn: reroute_count
		annotation SummarizationSetBy = Automatic

	column delay_count
		dataType: int64
		lineageTag: 2405f1f9-5af7-5254-a387-a752367ae9b6
		summarizeBy: sum
		sourceColumn: delay_count
		annotation SummarizationSetBy = Automatic

	column airport_flight_category
		dataType: string
		lineageTag: c9befd22-8c6f-56c2-b9d8-6b48c6506af6
		summarizeBy: none
		sourceColumn: airport_flight_category
		annotation SummarizationSetBy = Automatic

	column airport_visibility_sm
		dataType: decimal
		lineageTag: dad26634-9211-51b8-93e1-2076650ea7bd
		summarizeBy: none
		sourceColumn: airport_visibility_sm
		annotation SummarizationSetBy = Automatic

	column airport_ops_stress
		dataType: decimal
		lineageTag: df268ad8-bbf0-5b6c-b0ff-31f85d30ae06
		summarizeBy: none
		sourceColumn: airport_ops_stress
		annotation SummarizationSetBy = Automatic

	column active_airport_stations
		dataType: int64
		lineageTag: 412532ad-9241-5007-bbe8-e438565ce39f
		summarizeBy: none
		sourceColumn: active_airport_stations
		annotation SummarizationSetBy = Automatic

	column airport_stations_summary
		dataType: string
		lineageTag: 97ef433e-482a-5c15-ac61-e1725c531ead
		summarizeBy: none
		sourceColumn: airport_stations_summary
		annotation SummarizationSetBy = Automatic

	column trend_avg_interest
		dataType: decimal
		lineageTag: 452f32bd-ea6d-566a-b06a-28e2a5ac2fd2
		summarizeBy: none
		sourceColumn: trend_avg_interest
		annotation SummarizationSetBy = Automatic

	column fred_series_count
		dataType: int64
		lineageTag: 9cc1cab8-567a-5c42-860f-a47853610f0f
		summarizeBy: none
		sourceColumn: fred_series_count
		annotation SummarizationSetBy = Automatic

	column infrastructure_failure_risk
		dataType: decimal
		lineageTag: 733388b6-7ef9-55aa-8ab9-5148f80d9351
		summarizeBy: sum
		sourceColumn: infrastructure_failure_risk
		annotation SummarizationSetBy = Automatic

	column infrastructure_fatigue_risk
		dataType: decimal
		lineageTag: c1a93205-8a78-5c15-9024-e887e3a407d6
		summarizeBy: sum
		sourceColumn: infrastructure_fatigue_risk
		annotation SummarizationSetBy = Automatic

	column bridge_risk_score
		dataType: decimal
		lineageTag: f1da6e14-c3db-5f04-a837-88cea7e9c17f
		summarizeBy: none
		sourceColumn: bridge_risk_score
		annotation SummarizationSetBy = Automatic

	column road_surface_risk_score
		dataType: decimal
		lineageTag: d4f49568-108b-5f82-86a2-dd4872d48a77
		summarizeBy: none
		sourceColumn: road_surface_risk_score
		annotation SummarizationSetBy = Automatic

	column open_infrastructure_requests
		dataType: int64
		lineageTag: 95190a7c-be7f-5272-bcf2-b9c1c2e3cc2a
		summarizeBy: sum
		sourceColumn: open_infrastructure_requests
		annotation SummarizationSetBy = Automatic

	column infrastructure_summary
		dataType: string
		lineageTag: 4700dc58-0772-5635-b0e7-a39222a34c22
		summarizeBy: none
		sourceColumn: infrastructure_summary
		annotation SummarizationSetBy = Automatic

	column data_refreshed_at
		dataType: string
		lineageTag: 90acab21-9fd9-5177-8823-5f42ed9b4bc3
		summarizeBy: none
		sourceColumn: data_refreshed_at
		annotation SummarizationSetBy = Automatic

	column last_weather_ingest_at
		dataType: string
		lineageTag: 0ecc6975-8574-5336-b126-54eab6f161b9
		summarizeBy: none
		sourceColumn: last_weather_ingest_at
		annotation SummarizationSetBy = Automatic

	column last_transit_ingest_at
		dataType: string
		lineageTag: 19cda07e-6bf3-5b44-bd25-53f2c4929e40
		summarizeBy: none
		sourceColumn: last_transit_ingest_at
		annotation SummarizationSetBy = Automatic

	column last_civic311_ingest_at
		dataType: string
		lineageTag: 54908f52-7ef0-5fba-a823-886a889565ad
		summarizeBy: none
		sourceColumn: last_civic311_ingest_at
		annotation SummarizationSetBy = Automatic

	column last_airport_ingest_at
		dataType: string
		lineageTag: ec380892-977f-57de-9679-da2959b135a4
		summarizeBy: none
		sourceColumn: last_airport_ingest_at
		annotation SummarizationSetBy = Automatic

	measure 'City Stress Index' = AVERAGE(CityPulseSnapshot[city_stress_index])
		formatString: 0.0
		lineageTag: 96c842f7-fcb6-5afa-aacf-657c1de8088b

	measure 'Active Transit Alerts' = SUM(CityPulseSnapshot[active_transit_alerts])
		formatString: #,0
		lineageTag: c22d0b04-58c6-59a8-a7b8-ba48a04ce863

	measure 'Active NOAA Alerts' = SUM(CityPulseSnapshot[active_noaa_alerts])
		formatString: #,0
		lineageTag: ba942c64-41b8-59dc-bb5c-83bb9b68d30c

	measure 'Avg Precip %' = AVERAGE(CityPulseSnapshot[avg_precip_pct_next_periods])
		formatString: 0.0
		lineageTag: 80704d93-2c01-5bd8-88ec-c0d76cff2821

	measure 'Transit Load Score' = AVERAGE(CityPulseSnapshot[transit_load_score])
		formatString: 0.0
		lineageTag: fba24624-1ba9-5b79-a7a8-38b03a5415ec

	measure 'Weather Risk Score' = AVERAGE(CityPulseSnapshot[weather_risk_score])
		formatString: 0.0
		lineageTag: cb452219-f0ed-5243-becd-4fb69654fd0a

	measure 'Precip Risk Score' = AVERAGE(CityPulseSnapshot[precip_risk_score])
		formatString: 0.0
		lineageTag: acbe8805-5f10-5d31-a462-107f35927d5a

	measure 'Disruption Ratio Score' = AVERAGE(CityPulseSnapshot[disruption_ratio_score])
		formatString: 0.0
		lineageTag: 072cdd25-b13a-50a9-a376-8f7c01446b4f

	measure 'Reroute Count' = SUM(CityPulseSnapshot[reroute_count])
		formatString: #,0
		lineageTag: be74c5da-80cd-5e06-8bb4-f5b634d3ea50

	measure 'Trend Avg Interest' = AVERAGE(CityPulseSnapshot[trend_avg_interest])
		formatString: 0.0
		lineageTag: 113123d7-469b-5c52-8be2-ffba6005e5a0

	measure 'Airport Visibility (sm)' = AVERAGE(CityPulseSnapshot[airport_visibility_sm])
		formatString: 0.0
		lineageTag: 918ab3a7-54af-5aad-9627-890d458fc1f2

	measure 'Metro Airport Ops Stress' = MAX(CityPulseSnapshot[airport_ops_stress])
		formatString: 0.0
		lineageTag: 9593880d-197a-5245-80c1-6d6e431e9c27

	measure 'Active Airport Stations' = MAX(CityPulseSnapshot[active_airport_stations])
		formatString: #,0
		lineageTag: 36fd994f-0ede-5fbc-9fb3-b7d41ea424b1

	measure 'Infrastructure Failure Risk' = MAX(CityPulseSnapshot[infrastructure_failure_risk])
		formatString: 0.0
		lineageTag: 873a7a85-73d5-5241-a8b0-57a4076bb006

	measure 'Infrastructure Fatigue Risk' = MAX(CityPulseSnapshot[infrastructure_fatigue_risk])
		formatString: 0.0
		lineageTag: ccdf1875-65d8-5cd7-bcf9-3c72f46ca508

	measure 'Bridge Risk Score' = MAX(CityPulseSnapshot[bridge_risk_score])
		formatString: 0.0
		lineageTag: a9d76787-2eec-5fcf-8923-58e8d3474c52

	measure 'Road Surface Risk Score' = MAX(CityPulseSnapshot[road_surface_risk_score])
		formatString: 0.0
		lineageTag: db9d2d06-3155-5461-9c97-6595ee9d1f4a

	measure 'Open Infrastructure Requests' = MAX(CityPulseSnapshot[open_infrastructure_requests])
		formatString: #,0
		lineageTag: 2baf7e17-84f8-5a24-904c-6d4a992ad33a

	partition CityPulseSnapshot-6a9ee8ad-712d-5e82-b3a9-ef8e00d8601d = m
		mode: import
		source =
			let
				Source = Csv.Document(
					File.Contents("C:/Users/prendleman/AppData/Local/Temp/pytest-of-prendleman/pytest-48/test_build_pbip_blank_pages0/generated/chicago/data/CityPulseSnapshot.csv"),
					[Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
				),
				#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				#"Changed Column Types" = Table.TransformColumnTypes(
					#"Promoted Headers",
					{
					{"city", type text},
					{"snapshot_at", type text},
					{"city_stress_index", type number},
					{"transit_load_score", type number},
					{"weather_risk_score", type number},
					{"precip_risk_score", type number},
					{"disruption_ratio_score", type number},
					{"active_transit_alerts", Int64.Type},
					{"active_noaa_alerts", Int64.Type},
					{"avg_precip_pct_next_periods", type number},
					{"reroute_count", Int64.Type},
					{"delay_count", Int64.Type},
					{"airport_flight_category", type text},
					{"airport_visibility_sm", type number},
					{"airport_ops_stress", type number},
					{"active_airport_stations", Int64.Type},
					{"airport_stations_summary", type text},
					{"trend_avg_interest", type number},
					{"fred_series_count", Int64.Type},
					{"infrastructure_failure_risk", type number},
					{"infrastructure_fatigue_risk", type number},
					{"bridge_risk_score", type number},
					{"road_surface_risk_score", type number},
					{"open_infrastructure_requests", Int64.Type},
					{"infrastructure_summary", type text},
					{"data_refreshed_at", type text},
					{"last_weather_ingest_at", type text},
					{"last_transit_ingest_at", type text},
					{"last_civic311_ingest_at", type text},
					{"last_airport_ingest_at", type text}
					}
				)
			in
				#"Changed Column Types"

	annotation PBI_ResultType = Table

