table OsmAmenitySummary
	lineageTag: fbc85b32-da4a-5dbc-8673-29f20666fe45

	column city
		dataType: string
		lineageTag: 3fc20157-784a-5966-b5cc-94ebefe323da
		summarizeBy: none
		sourceColumn: city
		annotation SummarizationSetBy = Automatic

	column snapshot_at
		dataType: string
		lineageTag: 5c22aab4-e468-53ce-ba63-26c15060ada5
		summarizeBy: none
		sourceColumn: snapshot_at
		annotation SummarizationSetBy = Automatic

	column amenity
		dataType: string
		lineageTag: 5c8dc715-ad08-54c9-8b8a-27cf8cd48047
		summarizeBy: none
		sourceColumn: amenity
		annotation SummarizationSetBy = Automatic

	column poi_count
		dataType: int64
		lineageTag: 9cb3d735-b620-5117-83ea-f41c8da5e162
		summarizeBy: none
		sourceColumn: poi_count
		annotation SummarizationSetBy = Automatic

	partition OsmAmenitySummary-ebb540be-e118-5722-affb-8e0a4523e8bb = m
		mode: import
		source =
			let
				Source = Csv.Document(
					File.Contents("G:/My Drive/aq_wp_selenium_bot/aq-pulsegrid/generated_reports/chicago/data/OsmAmenitySummary.csv"),
					[Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
				),
				#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				#"Changed Column Types" = Table.TransformColumnTypes(
					#"Promoted Headers",
					{
					{"city", type text},
					{"snapshot_at", type text},
					{"amenity", type text},
					{"poi_count", Int64.Type}
					}
				)
			in
				#"Changed Column Types"

	annotation PBI_ResultType = Table

