table PbipStudioCatalog
	lineageTag: dde516a9-acc9-5c7c-9d08-120b52a00951

	column city
		dataType: string
		lineageTag: abe22ce1-2235-56ef-9cf6-f7260a0b7f62
		summarizeBy: none
		sourceColumn: city
		annotation SummarizationSetBy = Automatic

	column snapshot_at
		dataType: string
		lineageTag: 191e4448-5e53-5e70-b1e6-1b545cbbfe06
		summarizeBy: none
		sourceColumn: snapshot_at
		annotation SummarizationSetBy = Automatic

	column table_name
		dataType: string
		lineageTag: 86bf9ea0-46fb-57b2-811b-5724798939db
		summarizeBy: none
		sourceColumn: table_name
		annotation SummarizationSetBy = Automatic

	column source_path
		dataType: string
		lineageTag: 253e0ae8-563c-5015-aa49-ff6023054f15
		summarizeBy: none
		sourceColumn: source_path
		annotation SummarizationSetBy = Automatic

	column column_count
		dataType: int64
		lineageTag: 107f48d3-26e9-5f50-8105-0e79a270bafa
		summarizeBy: none
		sourceColumn: column_count
		annotation SummarizationSetBy = Automatic

	column columns_list
		dataType: string
		lineageTag: c1f8881e-b31e-5a79-90cd-4f670d058be1
		summarizeBy: none
		sourceColumn: columns_list
		annotation SummarizationSetBy = Automatic

	partition PbipStudioCatalog-005b86c4-48e4-54fa-b280-b9e5abc836f7 = m
		mode: import
		source =
			let
				Source = Csv.Document(
					File.Contents("C:/Users/prendleman/AppData/Local/Temp/pytest-of-prendleman/pytest-48/test_build_pbip_structure0/generated/chicago/data/PbipStudioCatalog.csv"),
					[Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
				),
				#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				#"Changed Column Types" = Table.TransformColumnTypes(
					#"Promoted Headers",
					{
					{"city", type text},
					{"snapshot_at", type text},
					{"table_name", type text},
					{"source_path", type text},
					{"column_count", Int64.Type},
					{"columns_list", type text}
					}
				)
			in
				#"Changed Column Types"

	annotation PBI_ResultType = Table

