table InfrastructureAssetSummary
	lineageTag: b509cb93-e61f-5d7d-93d0-1acfae6d9c27

	column city
		dataType: string
		lineageTag: a780eaf6-f099-58ff-bb28-fed5a6e4d77b
		summarizeBy: none
		sourceColumn: city
		annotation SummarizationSetBy = Automatic

	column snapshot_at
		dataType: string
		lineageTag: d4038a4e-961c-5cd1-9ceb-e59ac3c89c55
		summarizeBy: none
		sourceColumn: snapshot_at
		annotation SummarizationSetBy = Automatic

	column asset_class
		dataType: string
		lineageTag: 38c6a6e5-1ea9-5feb-95a4-f364bdb547c2
		summarizeBy: none
		sourceColumn: asset_class
		annotation SummarizationSetBy = Automatic

	column risk_tier
		dataType: string
		lineageTag: 92f0ff53-ce19-56f7-99eb-93b50b3e8171
		summarizeBy: none
		sourceColumn: risk_tier
		annotation SummarizationSetBy = Automatic

	column request_type
		dataType: string
		lineageTag: 755da8f9-0e50-52e6-b476-61c431c20c70
		summarizeBy: none
		sourceColumn: request_type
		annotation SummarizationSetBy = Automatic

	column request_count
		dataType: int64
		lineageTag: 8dfdbd80-f16e-5f7a-8882-28673f2afdfa
		summarizeBy: sum
		sourceColumn: request_count
		annotation SummarizationSetBy = Automatic

	measure 'Request Count' = SUM(InfrastructureAssetSummary[request_count])
		formatString: #,0
		lineageTag: a65565c1-0f15-5a7f-854a-3a765d65e19d

	partition InfrastructureAssetSummary-ef296f9e-854b-581d-bc2c-0ba89b78ec95 = m
		mode: import
		source =
			let
				Source = Csv.Document(
					File.Contents("G:/My Drive/aq_wp_selenium_bot/aq-pulsegrid/generated_reports/platform/data/InfrastructureAssetSummary.csv"),
					[Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
				),
				#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				#"Changed Column Types" = Table.TransformColumnTypes(
					#"Promoted Headers",
					{
					{"city", type text},
					{"snapshot_at", type text},
					{"asset_class", type text},
					{"risk_tier", type text},
					{"request_type", type text},
					{"request_count", Int64.Type}
					}
				)
			in
				#"Changed Column Types"

	annotation PBI_ResultType = Table

