table InfrastructureRequestDetail
	lineageTag: e3b94eb1-82f4-53c2-89d2-05c901415de9

	column city
		dataType: string
		lineageTag: 4a2cf496-7961-5608-9c60-0f51b4c19f15
		summarizeBy: none
		sourceColumn: city
		annotation SummarizationSetBy = Automatic

	column snapshot_at
		dataType: string
		lineageTag: 474d56c7-f25c-583a-a653-474e47cafe60
		summarizeBy: none
		sourceColumn: snapshot_at
		annotation SummarizationSetBy = Automatic

	column request_id
		dataType: string
		lineageTag: 932e5c9c-564e-598b-9355-f9afc9b0b9c2
		summarizeBy: none
		sourceColumn: request_id
		annotation SummarizationSetBy = Automatic

	column request_type
		dataType: string
		lineageTag: 7ffa53ce-f5af-5e5a-983f-35ef4ca686bc
		summarizeBy: none
		sourceColumn: request_type
		annotation SummarizationSetBy = Automatic

	column descriptor
		dataType: string
		lineageTag: a73608a8-a86e-59d0-a058-a59e74deea2b
		summarizeBy: none
		sourceColumn: descriptor
		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: 1663b35a-767d-54d5-82c2-027cc2a69fbb
		summarizeBy: none
		sourceColumn: status
		annotation SummarizationSetBy = Automatic

	column asset_class
		dataType: string
		lineageTag: 24610736-046d-5712-a00a-309e7828999a
		summarizeBy: none
		sourceColumn: asset_class
		annotation SummarizationSetBy = Automatic

	column risk_tier
		dataType: string
		lineageTag: 431e6003-dd1b-550f-8fa3-f56b79ef8a30
		summarizeBy: none
		sourceColumn: risk_tier
		annotation SummarizationSetBy = Automatic

	column failure_risk_score
		dataType: decimal
		lineageTag: dea431b0-c41d-5de5-9a4c-c3abf74d7fba
		summarizeBy: sum
		sourceColumn: failure_risk_score
		annotation SummarizationSetBy = Automatic

	partition InfrastructureRequestDetail-adf7fec8-62a5-528c-97ab-1d120c69496f = m
		mode: import
		source =
			let
				Source = Csv.Document(
					File.Contents("G:/My Drive/aq_wp_selenium_bot/aq-pulsegrid/generated_reports/platform/data/InfrastructureRequestDetail.csv"),
					[Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
				),
				#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				#"Changed Column Types" = Table.TransformColumnTypes(
					#"Promoted Headers",
					{
					{"city", type text},
					{"snapshot_at", type text},
					{"request_id", type text},
					{"request_type", type text},
					{"descriptor", type text},
					{"status", type text},
					{"asset_class", type text},
					{"risk_tier", type text},
					{"failure_risk_score", type number}
					}
				)
			in
				#"Changed Column Types"

	annotation PBI_ResultType = Table

