table TransitAlertDetail
	lineageTag: 44b40a2d-7ed1-590e-bc4b-1558c2709931

	column city
		dataType: string
		lineageTag: e35608b8-fdbb-5c96-9b2e-7979f62f9eb7
		summarizeBy: none
		sourceColumn: city
		annotation SummarizationSetBy = Automatic

	column snapshot_at
		dataType: string
		lineageTag: ed1d7466-56ef-528b-a341-255bd61bcaa4
		summarizeBy: none
		sourceColumn: snapshot_at
		annotation SummarizationSetBy = Automatic

	column hex_id
		dataType: string
		lineageTag: 0236826a-596d-5673-8f9b-783ccc56c788
		summarizeBy: none
		sourceColumn: hex_id
		annotation SummarizationSetBy = Automatic

	column neighborhood
		dataType: string
		lineageTag: 978c5423-9b94-538d-b3ab-7da31c77be5f
		summarizeBy: none
		sourceColumn: neighborhood
		annotation SummarizationSetBy = Automatic

	column alert_id
		dataType: string
		lineageTag: ef8fa41b-8553-505e-b60b-70e240a478eb
		summarizeBy: none
		sourceColumn: alert_id
		annotation SummarizationSetBy = Automatic

	column headline
		dataType: string
		lineageTag: 5388cdb1-d74e-5b0a-93d1-9c49bd5f3531
		summarizeBy: none
		sourceColumn: headline
		annotation SummarizationSetBy = Automatic

	column short_description
		dataType: string
		lineageTag: 73818b4a-1ff3-53f9-a81e-4558029731f4
		summarizeBy: none
		sourceColumn: short_description
		annotation SummarizationSetBy = Automatic

	column severity
		dataType: string
		lineageTag: acbca49f-2aef-5d4c-9275-0196b9f916fc
		summarizeBy: none
		sourceColumn: severity
		annotation SummarizationSetBy = Automatic

	column service
		dataType: string
		lineageTag: 2b491d01-f41c-56d6-8bbe-dbd68677e305
		summarizeBy: none
		sourceColumn: service
		annotation SummarizationSetBy = Automatic

	column alert_category
		dataType: string
		lineageTag: 288fb034-162c-5d2d-a81c-db3ebf36570c
		summarizeBy: none
		sourceColumn: alert_category
		annotation SummarizationSetBy = Automatic

	measure 'Transit Alert Count' = COUNTROWS(TransitAlertDetail)
		formatString: #,0
		lineageTag: 45d4e427-f9cf-5dac-a499-12f993541bd9

	partition TransitAlertDetail-224b57b1-599b-5303-91a2-f5818b6ac8c2 = m
		mode: import
		source =
			let
				Source = Csv.Document(
					File.Contents("G:/My Drive/aq_wp_selenium_bot/aq-pulsegrid/generated_reports/platform/data/TransitAlertDetail.csv"),
					[Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
				),
				#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				#"Changed Column Types" = Table.TransformColumnTypes(
					#"Promoted Headers",
					{
					{"city", type text},
					{"snapshot_at", type text},
					{"hex_id", type text},
					{"neighborhood", type text},
					{"alert_id", type text},
					{"headline", type text},
					{"short_description", type text},
					{"severity", type text},
					{"service", type text},
					{"alert_category", type text}
					}
				)
			in
				#"Changed Column Types"

	annotation PBI_ResultType = Table

